;;; Compiled snippets and support files for `css-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'css-mode
		     '(("-v" "$1: $2;\n-webkit-$1: $2;\n-moz-$1: $2;\n-ms-$1: $2;\n-o-$1: $2;" "-vendor-prefix" nil nil nil "/home/liam/.emacs.d/snippets/css-mode/v" nil nil)
		       ("padt" "padding-top: $1;" "padding-top: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/padt" nil nil)
		       ("padr" "padding-right: $1;" "padding-right: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/padr" nil nil)
		       ("padl" "padding-left: $1;" "padding-left: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/padl" nil nil)
		       ("padb" "padding-bottom: $1;" "padding-bottom: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/padb" nil nil)
		       ("pad.top" "padding-top: $1;" "padding-top: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/pad.top" nil nil)
		       ("pad.right" "padding-right: $1;" "padding-right: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/pad.right" nil nil)
		       ("pad.padding" "padding: ${top} ${right} ${bottom} ${left};" "padding: top right bottom left" nil nil nil "/home/liam/.emacs.d/snippets/css-mode/pad.padding" nil nil)
		       ("pad.pad" "padding: $1;" "padding: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/pad.pad" nil nil)
		       ("pad.left" "padding-left: $1;" "padding-left: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/pad.left" nil nil)
		       ("pad.bottom" "padding-bottom: $1;" "padding-bottom: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/pad.bottom" nil nil)
		       ("pad" "padding: $1;" "padding: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/pad" nil nil)
		       ("mart" "margin-top: $1;" "margin-top: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/mart" nil nil)
		       ("marr" "margin-right: $1;" "margin-right: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/marr" nil nil)
		       ("marl" "margin-left: $1;" "margin-left: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/marl" nil nil)
		       ("marb" "margin-bottom: $1;" "margin-bottom: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/marb" nil nil)
		       ("mar.top" "margin-top: $1;" "margin-top: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/mar.top" nil nil)
		       ("mar.right" "margin-right: $1;" "margin-right: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/mar.right" nil nil)
		       ("mar.margin" "margin: ${top} ${right} ${bottom} ${left};" "margin top right bottom left" nil nil nil "/home/liam/.emacs.d/snippets/css-mode/mar.margin" nil nil)
		       ("mar.mar" "margin: $1;" "margin: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/mar.mar" nil nil)
		       ("mar.left" "margin-left: $1;" "margin-left: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/mar.left" nil nil)
		       ("mar.bottom" "margin-bottom: $1;" "margin-bottom: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/mar.bottom" nil nil)
		       ("mar" "margin: $1;" "margin: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/mar" nil nil)
		       ("fs" "font-size: ${12px};" "font-size: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/fs" nil nil)
		       ("ff" "font-family: $1;" "font-family: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/ff" nil nil)
		       ("dispn" "display: none;" "display: none" nil nil nil "/home/liam/.emacs.d/snippets/css-mode/dispn" nil nil)
		       ("dispi" "display: inline;" "display: inline" nil nil nil "/home/liam/.emacs.d/snippets/css-mode/dispi" nil nil)
		       ("dispb" "display: block;" "display: block" nil nil nil "/home/liam/.emacs.d/snippets/css-mode/dispb" nil nil)
		       ("disp.none" "display: none;" "display: none" nil nil nil "/home/liam/.emacs.d/snippets/css-mode/disp.none" nil nil)
		       ("disp.inline" "display: inline;" "display: inline" nil nil nil "/home/liam/.emacs.d/snippets/css-mode/disp.inline" nil nil)
		       ("disp.block" "display: block;" "display: block" nil nil nil "/home/liam/.emacs.d/snippets/css-mode/disp.block" nil nil)
		       ("cl" "clear: $1;" "clear: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/cl" nil nil)
		       ("bor" "border: ${1:1px} ${2:solid} #${3:999};" "border size style color" nil nil nil "/home/liam/.emacs.d/snippets/css-mode/bor" nil nil)
		       ("bgi" "background-image: url($1);\n" "background-image: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/bgi" nil nil)
		       ("bg.1" "background-image: url($1);" "background-image: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/bg.1" nil nil)
		       ("bg" "background-color: #${1:DDD};" "background-color: ..." nil nil nil "/home/liam/.emacs.d/snippets/css-mode/bg" nil nil)))


;;; Do not edit! File generated at Tue Dec 19 11:32:39 2023
